import React from "react";

export default function DisclaimerPage() {
  return (
    <div className="hog-grid min-h-screen pb-20 pt-10">
      <main className="max-w-3xl mx-auto px-6 py-12 bg-card-bg border-2 border-border-custom rounded-[32px] shadow-[6px_6px_0px_0px_rgba(43,43,43,1)] dark:shadow-[6px_6px_0px_0px_rgba(255,255,255,1)]">
        <h1 className="font-serif text-3xl md:text-5xl font-bold tracking-tight text-text-base mb-2">
          Disclaimer
        </h1>
        <p className="font-mono text-xs text-text-muted mb-8">
          Effective Date: July 7, 2026
        </p>

        <div className="prose prose-neutral dark:prose-invert max-w-none text-xs md:text-sm text-text-muted space-y-6 leading-relaxed">
          <p>
            The information provided by <strong>Jayant Web & AI Systems</strong> ("we", "our", or "us") on our website is for general informational purposes only. All information on the site is provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the site.
          </p>

          <h2 className="font-serif text-lg font-bold text-text-base pt-4 border-t border-border-custom/50">
            Professional Disclaimer
          </h2>
          <p>
            The site cannot and does not contain professional technical, legal, or financial advice. The technical and software information is provided for general informational and educational purposes only and is not a substitute for professional consultation. Before taking any actions based upon such information, we encourage you to consult with the appropriate professionals. We do not provide any kind of engineering guarantees other than those agreed upon in signed written service SLAs.
          </p>

          <h2 className="font-serif text-lg font-bold text-text-base pt-4 border-t border-border-custom/50">
            External Links Disclaimer
          </h2>
          <p>
            The site may contain (or you may be sent through the site) links to other websites or content belonging to or originating from third parties. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us. We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through the site.
          </p>

          <h2 className="font-serif text-lg font-bold text-text-base pt-4 border-t border-border-custom/50">
            AI Tooling & Automation Outputs
          </h2>
          <p>
            Our software integrates generative AI technologies (including LLMs, RAG databases, and automation APIs). Outputs generated by these systems are subject to probabilistic model limits. While we build robust guardrails, we are not responsible for any model hallucinations or errors arising from unverified AI actions on production workloads.
          </p>

          <h2 className="font-serif text-lg font-bold text-text-base pt-4 border-t border-border-custom/50">
            Contact Us
          </h2>
          <p>
            If you have any questions about this disclaimer, please contact us at: <a href="mailto:jayantwebaisystems@gmail.com" className="text-primary hover:underline">jayantwebaisystems@gmail.com</a>.
          </p>
        </div>
      </main>
    </div>
  );
}
